#!/bin/sh

#Testing CloudStation
#LINKSTATION=1 means the build is for the LinkStation
#LINKSTATION=0 means the build is for the CloudStation
LINKSTATION=1

if [ $LINKSTATION -eq 1 ]; then
	VERSION=v173
	VERSIONDOT="1.73"
else
	VERSION=113
	VERSIONDOT="1.13"
	SUBVERSION=2.35
fi

SRC=./src
FIRMWARES=./firmwares
RESOURCES=./resources
#This worked fine under CentOS 7 but Debian uses dash instead of bash and the shell interpreter which seems to have issues with it.
#VERSIONDOT="${VERSION:0:1}.${VERSION:1}"
#This works under Debian but it was not tested under CentOS.
#VERSIONDOT="`echo $VERSION | head -c 1`.`echo $VERSION | tail -c 3`"
if [ $LINKSTATION -eq 1 ]; then
	FIRMWARESHELL="$RESOURCES/ls_series-$VERSION"
	FIRMWAREZIP="$FIRMWARES/ls_series-$VERSION.zip"
	HDDROOTFSPATH="$FIRMWARESHELL/LinkStation_FW$VERSIONDOT"
else
	FIRMWARESHELL="$RESOURCES/cloudstor-firmware-build-$VERSIONDOT-$SUBVERSION"
	FIRMWAREZIP="$FIRMWARES/cloudstor-firmware-build-$VERSIONDOT-$SUBVERSION.zip"
	HDDROOTFSPATH="$FIRMWARESHELL"
fi
FIRMWARESBACKOUT=".."
FIRMWARESHELLBACKOUT="../.."
TMPFOLDER=./tmp-compile
TMPFOLDERBACKOUT=".."

WEBUI=$FIRMWARES/utorrent-webui.2013052820184444.zip
MINIUI=$FIRMWARES/utorrent-miniui.2011042418543088.zip

TRANSMISSIONSTABLE_VERSION=2.77
TRANSMISSIONLATEST_VERSION=2.84
TRANSMISSIONCOMPILED=1

OLDWIN=nasnavi-266.exe
OLDOSX=nasnavi-266.dmg.zip
NASNAVIWIN=$FIRMWARES/nasnavi-282.zip
NASNAVIOSX=$FIRMWARES/nasnavi-282.dmg.zip

#FLEXGETVERSION=1.2.271
FLEXGETVERSION=1.2.349

#This is only usable on my own machine - GaryT
#FINALOUTPUTFULL=/media/sf_LinuxShare
#FINALOUTPUTAUTO=/media/sf_LinuxShare/buffaloplex
FINALOUTPUTFULL=./compiled
FINALOUTPUTAUTO=./compiled/autoupdate

rm -rf $TMPFOLDER 2> /dev/null
mkdir $TMPFOLDER
