#!/bin/sh

Init_media()
{
	. /etc/melco/diskinfo
		PLEXFOLDER="tmpplexupdatetmp"
		if [ "${array1}" = "off" ] || [ "${array1}" = "" ] ; then
			if [ ! -d /mnt/disk1/share ] && [ "${disk1}" != "normal" ] && [ "${disk2}" = "normal" ] && [ -d /mnt/disk2/share ]; then
				if [ -d "/mnt/disk2/$PLEXFOLDER" ]; then
					rm -rf "/mnt/disk2/$PLEXFOLDER"
				fi
				media="/mnt/disk2/$PLEXFOLDER"
			else
				if [ -d "/mnt/disk1/$PLEXFOLDER" ]; then
					rm -rf "/mnt/disk1/$PLEXFOLDER"
				fi
				media="/mnt/disk1/$PLEXFOLDER"
			fi
		else
			if [ -d "/mnt/array1/$PLEXFOLDER" ]; then
				rm -rf "/mnt/array1/$PLEXFOLDER"
			fi
			media="/mnt/array1/$PLEXFOLDER"
		fi
	mkdir $media

}

DEBUG=0
if [ $DEBUG -eq 1 ]; then
	echo "Debug execution. Use it on a PC only."
	TMPPATH=./tmp
	PLEXROOT=~/plex
	if [ ! -d $TMPPATH ]; then
		mkdir $TMPPATH
	fi
	if [ ! -d $PLEXROOT ]; then
		mkdir $PLEXROOT
	fi
else
	echo "This should only be run on Buffalo Linkstation devices with custom firmware. Visit http://tomatosoft.hu/gadgets for more."
	Init_media
	TMPPATH=$media
	PLEXROOT=/usr/local/plexroot
fi

if [ $# -eq 1 ]; then
	PLEXFILE=$1
	echo "Predefined Plex file detected."
else
	echo "Trying to find latest Plex Media Server."
	wget https://plex.tv/downloads/1/archive -O $TMPPATH/plexversions
	if [ $? -eq 0 ]; then
		echo "Successfully downloaded list of Plex versions."
		TMPVERSION=`grep "href=\"https://downloads.plex.tv/plex-media-server/[^\"]*-arm\.spk\".*data-event-label=\"arm5x\".*data-metric-custom2=\"Synology\"" $TMPPATH/plexversions | sed 's,.*href=\"https://downloads.plex.tv/plex-media-server/\([^\"]*\)-arm\.spk\".*data-event-label=\"arm5x\".*data-metric-custom2=\"Synology\".*,\1,' | head -1`
		PLEXFILE="https://downloads.plex.tv/plex-media-server/$TMPVERSION-arm.spk"
		else
		echo "Download of list of versions from plex.tv failed. Please add a link for manual download."
		exit
	fi
	rm $TMPPATH/plexversions
fi
PLEXBIN="`echo $PLEXFILE | sed 's,.*/,,'`"

echo "File to download: $PLEXFILE"
echo "Filename:	$PLEXBIN"
echo "Temporary directory: $TMPPATH"

echo "Downloading $PLEXBIN."
wget $PLEXFILE -O $TMPPATH/$PLEXBIN
if [ $? -ne 0 ]; then
	echo "Download of Plex Media Server ($PLEXBIN) failed."
	exit
fi

rm -rf $TMPPATH/unpack
mkdir $TMPPATH/unpack
tar -xf $TMPPATH/$PLEXBIN -C $TMPPATH/unpack
echo "Unpacking Plex, please wait."
tar -xzf $TMPPATH/unpack/package.tgz -C $PLEXROOT/lib
echo "Removing temporary files."
rm -rf $TMPPATH
echo "Done. Restart Plex manually from the graphical interface or by running \"/etc/init.d/plex.sh restart\" on the console."

