#!/bin/sh
#wget https://downloads.plex.tv/plex-media-server/0.9.11.7.803-87d0708/PlexMediaServer-0.9.11.7.803-87d0708-arm.spk
#wget https://downloads.plex.tv/plex-media-server/0.9.12.11.1406-8403350/PlexMediaServer-0.9.12.11.1406-8403350-arm.spk
wget https://downloads.plex.tv/plex-media-server/0.9.12.19.1537-f38ac80/PlexMediaServer-0.9.12.19.1537-f38ac80-arm.spk
